// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlertDirection string

const (
	AlertDirectionAbove AlertDirection = "above"
	AlertDirectionBelow AlertDirection = "below"
)

func (e *AlertDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertDirection(s)
	case string:
		*e = AlertDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertDirection: %T", src)
	}
	return nil
}

type NullAlertDirection struct {
	AlertDirection AlertDirection `json:"alert_direction"`
	Valid          bool           `json:"valid"` // Valid is true if AlertDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertDirection) Scan(value interface{}) error {
	if value == nil {
		ns.AlertDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertDirection), nil
}

type JobStatus string

const (
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
	JobStatusDone       JobStatus = "done"
	JobStatusFailed     JobStatus = "failed"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type NotificationChannel string

const (
	NotificationChannelTelegram NotificationChannel = "telegram"
	NotificationChannelPushover NotificationChannel = "pushover"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel `json:"notification_channel"`
	Valid               bool                `json:"valid"` // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

// Алерты пользователей на достижение цены
type Alert struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// Биржа (gate, bybit, binance)
	Exchange string `json:"exchange"`
	// Торговая пара в нормализованном виде (BTCUSDT)
	Symbol    string  `json:"symbol"`
	Price     float64 `json:"price"`
	Direction string  `json:"direction"`
	// Заметка пользователя к алерту
	Notes pgtype.Text `json:"notes"`
	// Активен ли алерт (можно отключить без удаления)
	IsActive bool `json:"is_active"`
	// Когда сработал алерт (NULL = ещё не сработал)
	FiredAt   pgtype.Timestamptz `json:"fired_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Очередь уведомлений (outbox pattern)
type NotificationJob struct {
	ID      int64  `json:"id"`
	AlertID int64  `json:"alert_id"`
	UserID  int64  `json:"user_id"`
	Channel string `json:"channel"`
	Status  string `json:"status"`
	// JSON с данными для отправки (текст сообщения, exchange, symbol, price)
	Payload []byte `json:"payload"`
	// Количество попыток отправки
	Attempts int32 `json:"attempts"`
	// Когда можно выполнить job (для retry с задержкой)
	RunAt     pgtype.Timestamptz `json:"run_at"`
	LastError pgtype.Text        `json:"last_error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Когда начали обработку (для отслеживания зависших)
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	// Когда job был завершён (done или failed)
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

// Пользователи бота
type User struct {
	ID         int64 `json:"id"`
	TelegramID int64 `json:"telegram_id"`
	// Pushover user key для отправки уведомлений
	PushoverUserKey pgtype.Text `json:"pushover_user_key"`
	// Включены ли уведомления через Pushover
	PushoverEnabled bool `json:"pushover_enabled"`
	// Включены ли уведомления через Telegram
	TelegramEnabled bool               `json:"telegram_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
