// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	ActivateAlert(ctx context.Context, arg ActivateAlertParams) error
	CleanupOldJobs(ctx context.Context) error
	CountActiveAlerts(ctx context.Context, userID int64) (int64, error)
	// ============================================================================
	// ALERT QUERIES
	// ============================================================================
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	DeactivateAlert(ctx context.Context, arg DeactivateAlertParams) error
	DeleteAlert(ctx context.Context, arg DeleteAlertParams) error
	FailJob(ctx context.Context, arg FailJobParams) error
	FetchActiveAlertsByKey(ctx context.Context, arg FetchActiveAlertsByKeyParams) ([]FetchActiveAlertsByKeyRow, error)
	FetchPendingJobs(ctx context.Context, limit int32) ([]NotificationJob, error)
	GetAlert(ctx context.Context, arg GetAlertParams) (Alert, error)
	GetAlertStats(ctx context.Context, userID int64) (GetAlertStatsRow, error)
	// ============================================================================
	// STATISTICS QUERIES (полезно для мониторинга)
	// ============================================================================
	GetJobStatsByChannel(ctx context.Context) ([]GetJobStatsByChannelRow, error)
	GetJobsByAlert(ctx context.Context, alertID int64) ([]NotificationJob, error)
	// ============================================================================
	// USER QUERIES
	// ============================================================================
	GetOrCreateUser(ctx context.Context, telegramID int64) (User, error)
	GetStuckJobs(ctx context.Context) ([]NotificationJob, error)
	GetUniqueActiveSubscriptions(ctx context.Context) ([]GetUniqueActiveSubscriptionsRow, error)
	GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error)
	// ============================================================================
	// NOTIFICATION JOB QUERIES
	// ============================================================================
	InsertNotificationJob(ctx context.Context, arg InsertNotificationJobParams) error
	ListActiveAlerts(ctx context.Context, userID int64) ([]Alert, error)
	ListAllUserAlerts(ctx context.Context, userID int64) ([]Alert, error)
	MarkAlertFired(ctx context.Context, id int64) error
	MarkJobDone(ctx context.Context, id int64) error
	MarkJobProcessing(ctx context.Context, id int64) error
	ResetStuckJobs(ctx context.Context) error
	RetryJob(ctx context.Context, arg RetryJobParams) error
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) error
}

var _ Querier = (*Queries)(nil)
